### ISSUE TITLE
EOPNOTSUPP on rpi

### ISSUE THREAD

**Issue by dholroyd** [irauta/linuxdvb#2]
I think some of the FFI values need to be architecture dependant; probably checked in values assume 64-bit pointers, so don't work on 32-bit linux.

e.g. `FE_SET_PROPERTY` needs to be `0x40086f52` on rpi -- the value checked in is `0x40106f52`, which results in `EOPNOTSUPP` on the pi.

(Still, I learned a bit about `ioctl()` today!)

**Comment by dholroyd** [comment]
Should add that I'd been trying to cross-compile from x86_64 (without understanding the above).

Will now actually try running codegen scripts on the pi itself!

**Comment by irauta** [comment]
Turns out I just learned something new about the ioctl numbers myself too. The size of the related data type is part of the number so the varying pointer sizes really do change the numbers. Obvious in hindsight, considering the used structs are passed to the number-generating macros.

The FE_* constant generation should probably be moved out of the codegen part, and produced with the ioctl-gen crate or similar. There's only handful of them, so it shouldn't be too bad - the API doesn't change often anyway. Lack of const fns makes incorporating struct sizes into regular constants impossible in stable Rust I think, so maybe FE_SET_PROPERTY and etc. should be turned into functions returning the ioctl number or something like that...

**Comment by irauta** [comment]
The ioctl number generation is now updated, at least the numbers for FE_SET_PROPERTY are 0x40106F52 in a 64-bit build and 0x40086F52 in a 32-bit build. Could not test if it really works on my machine, and after a cursory search it looks like the 32-bit compatibility on 64-bit kernels maybe just isn't there. Anyway, I'm still almost certain that the issue is now fixed, because of those numbers above.

There were also some changes in the public API of the crate, because I ended up updating dependencies (the old version didn't compile right away after and the dependency versions were nastily defined as * anyway). The bitflags crate works differently now that it is in version 1.0. The bitflag constants are now namespaced in structs so they didn't have to live in their own mods anymore. Now everything is just re-exported at the root level of the crate.

I think I will also change those constants into all caps to make the API a little more Rust-y ("to shut down compiler complaints" just didn't feel like a nice way to phrase it), but not today. Sorry for the churn!

**Comment by dholroyd** [comment]
Awesome!  It feels like its taken most of the time since my last comment for `bindgen` to compile on the pi, but now I don't need to figure it out.

I'd actually made some of those same adjustments for latest `bitflags`; it looks like you've done it properly.

Will try to the latest code over the weekend.

**Comment by dholroyd** [comment]
Great!

With those changes, I see no more `EOPNOTSUPP`, and the ioctl value looks good in strace output on the pi.

So the problem raised in this ticket is fixed; but, I do see `EINVAL` when trying to set more than one property in a single call.

DVB debugging gives the following in `dmesg` when the app receives `EINVAL`,

```
dtv_property_dump: SET tvp.cmd = 0x00000000 undefined
```

Maybe this is due to, 

https://github.com/irauta/linuxdvb/blob/f2c53cfabbad2ae4df98bfe3553b04f1eafafc57/src/frontend/ffi.rs#L521-L523

since,
 - `sizeof(struct dtv_property)` is 76 on x86_64, and 72 on the pi.
 - the definition of that union inside `struct dtv_property` has a `void *reserved2;` pointer

For the moment though, I'm making progress by performing multiple `fe.set_properties(..)` calls with one entry passed to each.

**Comment by irauta** [comment]
Yeah, looks like that reserved2 pointer is the culprit. I was already lamenting that now I need to hand-craft the entire property struct to make things work, but luckily I didn't get too far into that before remembering that regenerating the FFI types with an up-to-date bindgen might help, because it did!

Now the helper type uses the native union support, and that reserved2 field is now an actual pointer, so the size of the entire type should adjust depending on the target. Bunch of changes had to be done to make the code work with the new FFI types, hopefully I didn't break anything else in the process...

**Comment by dholroyd** [comment]
Perfect -- multiple properties in a single `fe.set_properties()` call now works as expected on the pi.

And I've worked out enough of the underlying DVB API to get a stream out of my device, so I can test the mpegts parser I've been working on.

Thanks so much for your help!

**Comment by irauta** [comment]
Glad to hear it's working now!
